name: deploy

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Compress Node.js application files into a zip file
        run: zip -r "nodejs_deploy-${{ github.sha }}.zip" ./client ./server ./.ebextensions server.js package.json package-lock.json

      - name: Upload the zip file to an S3 bucket
        run: aws s3 cp "nodejs_deploy-${{ github.sha }}.zip" s3://najia096-skillnet

      - name: Create a new application version in Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name flaskbb \
          --source-bundle S3Bucket="najia096-skillnet",S3Key="nodejs_deploy-${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}" \
          --region "us-east-1"

      - name: Update the Elastic Beanstalk environment with the new application version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name flaskbb-environment \
          --version-label "ver-${{ github.sha }}" \
          --region "us-east-1"
