# This workflow will deploy the application to the running environment whenever changes are pushed or pulled to the main branch

name: deploy

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - 'server/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
      
      - name: Build application
        run: |
          npm run build

      - name: Zip application
        run: |
          zip -r "flaskbb_deploy-${{ github.sha }}.zip" ./client ./server ./.ebextensions server.js package.json package-lock.json

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: flaskbb_application_artifact
          path: flaskbb_deploy-${{ github.sha }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" 

      - name: Upload application file to S3
        run: aws s3 cp flaskbb_deploy-${{ github.sha }}.zip s3://flaskbbapp

      - name: Create new application version
        run: |  
          aws elasticbeanstalk create-application-version \
          --application-name flaskbb \
          --source-bundle S3Bucket="flaskbbapp",S3Key="flaskbb_deploy-${{ github.sha }}.zip " \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy application
        run: aws elasticbeanstalk update-environment --environment-name flaskbb-environment --version-label "ver-${{ github.sha }}"
