name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit and integration tests
        run: npm test

      - name: Generate code coverage report
        run: npm run coverage

      - name: Start application
        run: npm start &

      - name: Run end-to-end tests
        run: npm run test:e2e
